name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 7
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
        
    - name: Install gradle 4
      uses: gradle/gradle-build-action@v2.1.3
      with:
        gradle-version: 4.4
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Generate Gradle wrapper
      run: gradle wrapper
      
    - name: Build with Gradle
      run: ./gradlew build
